services:
  seaweedfs:
    image: chrislusf/seaweedfs:4.28
    ports:
      - 8333:8333 # S3 API
      - 9333:9333 # master UI
      - 23646:23646 # admin UI
    volumes:
      - ./.s3-data:/data
    env_file: .env
    # environment:
    # - AWS_ACCESS_KEY_ID=
    # - AWS_SECRET_ACCESS_KEY=
    # - S3_BUCKET=
    command: mini -dir=/data
    restart: unless-stopped
